Alcancia-io/Alcancia-FrontEnd

lib/src/features/dashboard/presentation/dashboard_card.dart, lib/src/features/login/presentation/login_screen.dart, lib/src/features/registration/presentation/otp_screen.dart, lib/src/features/registration/presentation/registration_screen.dart, lib/src/features/welcome/presentation/welcome_screen.dart, lib/src/shared/components/alcancia_list_picker_dialog.dart
Change button dimensions according to figma
=> fix: buttons in welcome, login, registration, otp and registration modal

ios/Runner.xcodeproj/project.pbxproj, lib/src/features/dashboard/presentation/dashboard_card.dart, lib/src/features/login/presentation/login_screen.dart, lib/src/features/registration/presentation/otp_screen.dart, lib/src/features/registration/presentation/registration_screen.dart, lib/src/features/welcome/presentation/welcome_screen.dart, lib/src/shared/components/alcancia_dropdown.dart, lib/src/shared/components/alcancia_list_picker_dialog.dart
alcanciaDropdown widget was fixed to avoid overflow
=> fix and refactor alcanciaDropdown

lib/src/screens/dashboard/dashboard_controller.dart, lib/src/screens/dashboard/dashboard_screen.dart, lib/src/shared/components/dashboard/dashboard_card.dart, lib/src/shared/graphql/queries/walletbalance_query.dart, lib/src/shared/models/user_model.dart, lib/src/shared/provider/balance_provider.dart, lib/src/shared/provider/router_provider.dart, lib/src/shared/provider/user_provider.dart, lib/src/shared/services/user_service.dart
The balance is fetched every 10 seconds in the dashboard screen. This was a petition from Juandi and was made previously in the testflight branch but it is being added to develop through this PR.
For it to work I had to initialize the userservice in each of the functions that use it because if this is not done the graphql cache will show always the same result.
Make sure you are in the latest version of the backend or consuming the deployed backend.
Run the app, go to dashboard and wait 10 seconds for it to change
=> feat: fetch balance every 10 seconds

lib/src/features/registration/model/registration_controller.dart, lib/src/features/registration/model/user_registration_model.dart, lib/src/features/registration/presentation/otp_screen.dart, lib/src/features/registration/presentation/phone_registration_screen.dart, lib/src/features/registration/presentation/registration_screen.dart, lib/src/resources/colors/app_theme.dart, lib/src/screens/login/mfa_screen.dart, lib/src/shared/components/alcancia_text_field.dart, lib/src/shared/models/user_model.dart, lib/src/shared/provider/router_provider.dart
Moved phone number field from registration process to new screen
N/A
Run the app, and go through the registration process.
=> Phone registration screen

lib/src/shared/provider/router_provider.dart
Refactor redirect code
N/A
Use the app as usual, everything should work the same way it did before
Go through all possible screens, signing out should return to welcome screen.
N/A
=> refactor: gorouter redirect

lib/src/screens/dashboard/dashboard_screen.dart
Adds pull to refresh gesture in dashboard
N/A
Go to dashboard and pull down to refresh user information
=> feat: pull to refresh dashboard

lib/src/shared/components/dashboard/balance_carousel.dart
Removes unnecessary decimals when balance equals zero
N/A
N/A
=> fix: remove decimals when balance is zero

lib/src/screens/metamap/address_screen.dart
Fixes wrong state value being sent in Address Screen
=> fix: wrong state value sent in address

lib/src/features/registration/presentation/phone_registration_screen.dart
=> fix: t&c/privacy policy links

ios/Runner/Info.plist
=> chore: set iOS non-exempt encryption key to false

lib/src/screens/withdraw/withdraw_screen.dart, lib/src/shared/models/currency_asset.dart, lib/src/shared/models/transaction_model.dart
Updates target amount field in Withdraw screen after changing selected currency in dropdown
Also fixes withdraw asset shown in transactions list
=> fix: update target amount after changing currency

lib/src/shared/components/alcancia_toolbar.dart
=> fix: center title in AlcanciaToolbar

lib/src/features/user-profile/presentation/account_screen.dart, lib/src/features/user-profile/presentation/user_profile_screen.dart, lib/src/screens/checkout/checkout.dart, lib/src/screens/swap/components/currency_risk_card.dart
- Some fixes requested by users: 
- Check change password btn in account is not there anymore
- Check email does not show anymore on profile screen
- Check snackbar appears when copying Beneficiario
- Check a nicer error appears when there is an error with suarmi after trying to deposit
=> fix: ui details

lib/src/features/registration/presentation/registration_screen.dart, lib/src/screens/withdraw/withdraw_screen.dart, lib/src/shared/components/dashboard/balance_carousel.dart
=> fix: more ui changes

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Info.plist, lib/src/screens/onboarding/onboarding_screens.dart, lib/src/shared/services/exception_service.dart, pubspec.lock
Send user to welcome screen after going through onboarding screens
=> fix: welcome after onboarding

lib/src/screens/withdraw/withdraw_screen.dart, lib/src/shared/graphql/queries/me_query.dart, lib/src/shared/models/user_model.dart
=> feat: autofill CLABE

lib/src/screens/metamap/address_controller.dart, lib/src/screens/metamap/address_screen.dart, lib/src/screens/swap/swap_controller.dart, lib/src/screens/swap/swap_screen.dart
=> fix: update user after KYC

lib/src/shared/components/dashboard/balance_carousel.dart
=> feat: change user balance decimal font style

ios/Runner.xcodeproj/project.pbxproj, ios/ci_scripts/ci_pre_xcodebuild.sh
=> chore: xcode cloud env files and pod errors

lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/swap/swap_screen.dart
=> fix: missing investment localization

lib/src/features/user-profile/presentation/account_screen.dart
=> fix: disable change password button

lib/src/features/transactions-list/presentation/transactions_list_screen.dart, lib/src/shared/components/alcancia_transactions_list.dart
=> fix: empty transactions text color

android/app/build.gradle, android/app/google-services.json
=> chore: setup play store deployment

ios/Runner/GoogleService-Info.plist, ios/firebase_app_id_file.json, lib/firebase_options.dart
=> fix: iOS bundle id in firebase files

lib/src/screens/checkout/checkout.dart, lib/src/screens/metamap/address_controller.dart, lib/src/screens/metamap/address_screen.dart, lib/src/screens/swap/swap_controller.dart, lib/src/screens/swap/swap_screen.dart, lib/src/shared/models/checkout_model.dart, lib/src/shared/provider/router_provider.dart
=> fix: multiple suarmi orders on checkout

lib/src/screens/dashboard/dashboard_screen.dart
=> chore: remove verificaion status from home

lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/swap/swap_screen.dart
=> chore: add max deposit amount

lib/src/screens/swap/swap_screen.dart
=> chore: swap target currencies order

lib/src/shared/extensions/string_extensions.dart
Needs 1 uppercase, 3 lowercase, 1 number, 1 special characters, min 8 characters total
=> fix: password regex

lib/src/features/registration/presentation/gender_picker.dart, lib/src/shared/components/alcancia_date_picker.dart, lib/src/shared/components/alcancia_text_field.dart
=> fix: registration fields padding

pubspec.yaml
=> chore: update version number

lib/src/features/registration/presentation/registration_screen.dart
=> fix: emails in use

lib/src/screens/swap/swap_screen.dart, lib/src/screens/withdraw/withdraw_screen.dart, lib/src/shared/components/alcancia_dropdown.dart
Fix DOP withdrawal dropdown height and deposit minimum amount validation
N/A
=> fix/dop UI

android/build.gradle, lib/src/screens/checkout/checkout.dart, lib/src/screens/swap/swap_screen.dart
- [* ] fix
- fix Deposit
Make a deposit
empty
=> Fix deposit

lib/src/screens/deposit/crypto_deposit_screen.dart, pubspec.lock, pubspec.yaml
=> chore: change qrcode embedded png to svg

lib/src/resources/l10n/app_en.arb, lib/src/screens/swap/swap_screen.dart
=> Metamap Dom

lib/src/shared/models/transaction_model.dart
=> fix: transaction decoding

lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/deposit/deposit_option.dart, lib/src/screens/deposit/deposit_screen.dart
=> chore: add "coming soon" to crypto deposits

lib/src/shared/components/dashboard/balance_carousel.dart
=> chore: remove cUSD balance from carousel

android/app/build.gradle, ios/Podfile.lock, pubspec.lock, pubspec.yaml
=> fix: update package for android crash

lib/src/shared/components/dashboard/balance_carousel.dart
=> fix: Prevent scrolling for single item in Balance Carousel

lib/src/features/registration/presentation/registration_screen.dart, lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/dashboard/dashboard_controller.dart, lib/src/screens/dashboard/dashboard_screen.dart, lib/src/screens/swap/swap_screen.dart, lib/src/shared/components/alcancia_button.dart, lib/src/shared/components/dashboard/dashboard_actions.dart, lib/src/shared/models/kyc_status.dart, lib/src/shared/models/user_model.dart, lib/src/shared/provider/user_provider.dart
=> feat: update dashboard screen with KYC verification status

lib/main.dart, lib/src/screens/transfer/transfer_screen.dart
More responsive transfer screen 
Transfer screen dropdown height.
Vertical scroll implementation for horizontal screen cases.
- [* ] fix
- [ *] chore
=> Transfer screen height y field adjustment.

lib/src/shared/components/dashboard/dashboard_actions.dart
=> chore: change failed verification button color

lib/src/screens/login/login_screen.dart
=> fix: deny whitespaces in email login field

lib/src/features/registration/model/registration_controller.dart, lib/src/shared/services/auth_service.dart
=> fix: send email as lowercase to backend

lib/src/shared/services/auth_service.dart
=> fix: missing null check

lib/src/features/registration/presentation/phone_registration_screen.dart, lib/src/features/user-profile/presentation/user_profile_screen.dart
=> fix: update T&C and Privacy Policy links

lib/src/shared/components/alcancia_list_picker_dialog.dart
=> fix: fit phone country picker options

lib/src/screens/withdraw/crypto_withdraw_screen.dart
=> fix: tap to dismiss keyboard

lib/src/features/user-profile/presentation/user_profile_screen.dart, lib/src/resources/l10n/app_es.arb, lib/src/screens/chart/alcancia_line_chart.dart, pubspec.yaml
=> Correccion conflict merge

lib/src/features/registration/model/registration_controller.dart
=> fix: lowercase email in signup

lib/src/features/user-profile/presentation/user_profile_screen.dart, lib/src/screens/chart/alcancia_line_chart.dart, lib/src/screens/chart/line_chart_screen.dart, lib/src/shared/models/balance_history_model.dart
=> Mejoras Zendesk, LineChart

android/build.gradle, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
=> fix: gradle and package versions

pubspec.lock
=> fix: xcode 15 build

lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb
=> fix: referral text

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj
=> chore: upgrade cocapods

lib/src/shared/components/dashboard/balance_carousel.dart, lib/src/shared/provider/balance_provider.dart
=> Balance carousel

ios/Podfile.lock, lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/required_update/required_update_screen.dart, lib/src/shared/graphql/queries/get_currently_supported_app_version_query.dart, lib/src/shared/provider/router_provider.dart, lib/src/shared/services/version_service.dart, pubspec.lock, pubspec.yaml
=> feat: update required screen

lib/src/shared/components/alcancia_toolbar.dart, lib/src/shared/components/alcancia_transaction_item.dart, lib/src/shared/components/dashboard/balance_carousel.dart
=> fix: spacing/padding issues

lib/src/shared/provider/router_provider.dart
=> fix: android secure storage exception

lib/src/screens/transaction_detail/components/transaction_detail_item.dart, lib/src/screens/transaction_detail/transaction_detail.dart
Copy clipboard transaction id in transaction details.
- [* ] chore
=> Copy Clipboard transaction ID

lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/network_error/network_error_screen.dart, lib/src/shared/provider/router_provider.dart
=> feat: check internet connection

lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/account_verification.dart, lib/src/screens/login/login_screen.dart, lib/src/shared/provider/router_provider.dart
=> feat: add account verification screen

test/deposit/deposit_screen_test.dart
=> Test Widget Deposit Screen

lib/src/screens/transfer/transfer_screen.dart, lib/src/screens/withdraw/crypto_withdraw_screen.dart, lib/src/screens/withdraw/withdraw_screen.dart, lib/src/shared/components/dashboard/balance_carousel.dart, lib/src/shared/graphql/queries/walletbalance_query.dart, lib/src/shared/provider/balance_provider.dart
Carousel balance shows USDC only.
- [ *] fix
=> fix/Only USDC Carousel

lib/src/screens/transaction_detail/components/transaction_detail_item.dart, lib/src/screens/transaction_detail/transaction_detail.dart, lib/src/shared/components/alcancia_copy_clipboard.dart, lib/src/shared/components/deposit_info_item.dart
=> fix: transaction id copy to clipboard

lib/src/shared/components/decimal_input_formatter.dart
=> fix: take comma as decimal separator

lib/src/features/registration/presentation/phone_registration_screen.dart, lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb
=> fix: privacy policy localizations

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/src/shared/models/transaction_model.dart, pubspec.lock, pubspec.yaml
=> hotfix: metamap android

lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/account_verification.dart, lib/src/screens/login/login_controller.dart, lib/src/screens/login/login_screen.dart, lib/src/screens/login/mfa_screen.dart, lib/src/shared/graphql/mutations/complete_mfa_sign_in_mutation.dart, lib/src/shared/graphql/mutations/login_mutation.dart, lib/src/shared/graphql/mutations/signin_mutation.dart, lib/src/shared/models/MFAModel.dart, lib/src/shared/models/login_data_model.dart, lib/src/shared/services/auth_service.dart
Needs more testing, MFA codes stopped working
=> chore: new sign in flow

lib/src/screens/chart/alcancia_line_chart.dart
Fix balance history error when there's no balance to show.
- [* ] fix
=> fix line_chart when there's no data

lib/src/shared/components/alcancia_transaction_item.dart
Text USDC in transaction list to upper case.
=> chore/To upper case USDC text Transaction List

lib/src/screens/login/login_screen.dart
=> Password remembering

ios/Runner/Runner.entitlements, lib/src/screens/login/login_screen.dart
=> feat: ios login autofill

lib/src/features/registration/presentation/registration_screen.dart
=> fix: iOS keyboard type in registration

lib/main.dart, lib/src/screens/biometric/biometric_authentication_screen.dart, lib/src/screens/login/login_screen.dart, lib/src/shared/provider/router_provider.dart, lib/src/shared/services/biometric_service.dart
=> fix: twitching biometric screen

lib/src/screens/swap/swap_screen.dart, lib/src/screens/withdraw/withdraw_screen.dart, lib/src/shared/components/dashboard/dashboard_actions.dart
Commented out MXN and Mexico options in `swap_screen` and `withdraw_screen`
N/A
N/A
Everything else should work as usual
N/A
=> OINK-1351 - hotfix: temporally disable MXN deposit/withdrawal

ios/Runner/Info.plist, lib/src/screens/swap/swap_screen.dart
Remove the Exchange Rate component for MXN
=> hotfix: hide USDC<>MXN exchange rate

lib/src/features/registration/model/registration_controller.dart, lib/src/features/registration/presentation/otp_screen.dart, lib/src/features/registration/presentation/phone_registration_screen.dart, lib/src/features/user-profile/presentation/user_profile_screen.dart, lib/src/screens/dashboard/dashboard_controller.dart, lib/src/screens/login/login_screen.dart, lib/src/shared/graphql/mutations/delete_account_mutation.dart, lib/src/shared/graphql/queries/get_authenticated_user_query.dart, lib/src/shared/graphql/queries/index.dart, lib/src/shared/graphql/queries/is_authenticated_query.dart, lib/src/shared/graphql/queries/logout_query.dart, lib/src/shared/provider/router_provider.dart, lib/src/shared/services/auth_service.dart, lib/src/shared/services/user_service.dart
From issue #217 
Migrate `meQuery` to `getAuthenticatedUserQuery`.
This PR also includes fixes for sign in and sign up functionality that broke sometime during the latest backend changes.
Make sure to use staging env branch
Use the app as you normally would, everything should work as usual.
=> OINK-1347 - migrate me query

lib/src/screens/login/login_screen.dart, lib/src/screens/login/mfa_screen.dart
Biometrics Login (FaceID/TouchId) Are not working in Stage.
Fix biometrics when login... 
Enable biometrics in your account.
Login using biometrics.
=> fix/OINK-1368 | Biometrics Verification not Working in Staging

lib/src/shared/graphql/queries/user_phone_number_search_query.dart, lib/src/shared/services/user_service.dart
When Trying to do a Transfer to another Alcancia User, An Invalid Query Parameters error shows up.
Fix USDC transfer to another account.
=> hotfix/OINK-1371 | Transfer Screen Throwing Error

lib/src/screens/forgot_password/forgot_password.dart
_When going into the "Forgot Password" Page a weird messaging typo is shown.
Fix the thing...
Go to forgot pasword at login screen.
=> hotfix/OINK-1378 | Hotfix Forgot Password Messaging Error from Develop

lib/src/shared/models/external_withdrawal.dart
-Converted the Withdrawal amount to String, the expected type on the model.
-n/a
-Run a Crypto Withdrawal and you should see a successful message at the bottom after its completed
=> OINK-1385 | Fix Crypto Withdrawal Error

lib/src/screens/forgot_password/forgot_password.dart
=> Fix Stage Merge Conflicts 

lib/src/screens/forgot_password/forgot_password.dart
Hotfix error forgot password.
substitute last 4 digits phone to medium delivery in forgot password screen text.
Tab forgot password.
=> OINK-1387 | Forgot Password Error

lib/src/shared/services/metamap_service.dart, pubspec.lock, pubspec.yaml
=> Fixes iOS Deployment issues with CocoaPods Version mismatches

lib/src/screens/swap/swap_screen.dart
Fixes #297 
Changed the Source Currency getting set before the remote config values are retrieved
-Open Deposits page as MXN user, USD should be the default selected value
=> Fix: Incorrect Default Currency getting set

lib/src/screens/withdraw/withdraw_screen.dart
When creating a withdraw transaction MXN users are getting a SUARMI Error at the bottom preventing the withdraw
- [ *] fix
=> Fix/OINK-1428 | MXN Users getting Suarmi Error on Withdraw

lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/transfer/transfer_screen.dart
Fixes #283 and #282 
When going to the Transfer Process and inputting the same user's phone number there's an error message for this scenario that is not fully visible to the user cause its rendered underneath the NEXT button and that can cause confusion.
When going to the Transfer Process and inputting the same user's phone number there's an error message for this scenario that is not fully visible to the user cause its rendered underneath the NEXT button and that can cause confusion.
Fix visibility of errors in transfer screen.
- Type your own phone number
- Type a non-existing phone number. (Whatever comes up to your mind)
Test errors visibility.
=> OINK-1414 & OINK-1395 | Tranfer Funds error messages

lib/src/screens/withdraw/withdraw_screen.dart
Changes withdrawal amount Label to show currency
=> Change Label on Withdraw amount

lib/src/shared/graphql/mutations/refresh_token_mutation.dart, lib/src/shared/provider/router_provider.dart, lib/src/shared/services/auth_service.dart, lib/src/shared/services/biometric_service.dart
Closes #278 
Implements Refresh Token logic to avoid multiple unnecessary sign-ins
=> OINK-1412 | Implement Refresh Token

lib/src/resources/l10n/app_en.arb, lib/src/resources/l10n/app_es.arb, lib/src/screens/forgot_password/forgot_password.dart, lib/src/screens/swap/swap_screen.dart, lib/src/screens/transfer/transfer_screen.dart, lib/src/screens/withdraw/withdraw_screen.dart, lib/src/shared/graphql/mutations/refresh_token_mutation.dart, lib/src/shared/graphql/queries/forgot_password_query.dart, lib/src/shared/provider/router_provider.dart, lib/src/shared/services/auth_service.dart, lib/src/shared/services/biometric_service.dart
Includes:
- #278 
- #281 
- #282 
- #283
=> Release v1.5.9
